jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /pedido
      session:
         timeout: 21600s

spring:
   jpa:
      show:
         sql: true
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:adn
      username: sa
      password:
      hikari:
         poolName: pool
